### ISSUE TITLE
Error when build the bridge

### ISSUE THREAD

**Issue by yironglin** [NEWSLabNTU/carla_autoware_bridge_plus#1]
Hi, I recently followed the usage to install this bridge.
I set up the Autoware environment with: https://autowarefoundation.github.io/autoware-documentation/main/installation/autoware/docker-installation/

After `colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --cargo-args --release`, I get the error below:

> --- stderr: carla_autoware_bridge_plus                                                        
> error[E0433]: failed to resolve: could not find `moveit_msgs` in `r2r`
>   --> src/actor_node/traffic_light.rs:14:5
>    |
> 14 |     moveit_msgs::msg::OrientedBoundingBox,
>    |     ^^^^^^^^^^^ could not find `moveit_msgs` in `r2r`
> 
> error[E0433]: failed to resolve: could not find `moveit_msgs` in `r2r`
>  --> src/actor_node/traffic_sign.rs:6:36
>   |
> 6 |     builtin_interfaces::msg::Time, moveit_msgs::msg::OrientedBoundingBox, Node, Publisher,
>   |                                    ^^^^^^^^^^^ could not find `moveit_msgs` in `r2r`
> 
> error[E0433]: failed to resolve: could not find `carla_msgs` in `r2r`
>   --> src/actor_node/vehicle.rs:12:5
>    |
> 12 |     carla_msgs::msg::{CarlaEgoVehicleControl, CarlaEgoVehicleInfo, CarlaEgoVehicleInfoWheel},
>    |     ^^^^^^^^^^ could not find `carla_msgs` in `r2r`
> 
> error[E0433]: failed to resolve: could not find `moveit_msgs` in `r2r`
>   --> src/utils.rs:10:5
>    |
> 10 |     moveit_msgs::msg::OrientedBoundingBox,
>    |     ^^^^^^^^^^^ could not find `moveit_msgs` in `r2r`
> 
> error[E0283]: type annotations needed for `Publisher<T>`
>    --> src/actor_node/traffic_light.rs:27:9
>     |
> 27  |     let trigger_volume_pub = node.create_publisher(&format!("{prefix}/trigger_volume"), qos)?;
>     |         ^^^^^^^^^^^^^^^^^^        ---------------- type must be known at this point
>     |
>     = note: cannot satisfy `_: r2r::msg_types::WrappedTypesupport`
> note: required by a bound in `Node::create_publisher`
>    --> /home/yirong/.cargo/git/checkouts/r2r-8618b4115035fdcb/6644562/r2r/src/nodes.rs:568:12
>     |
> 568 |         T: WrappedTypesupport,
>     |            ^^^^^^^^^^^^^^^^^^ required by this bound in `Node::create_publisher`
> help: consider specifying the type argument in the function call
>     |
> 27  |     let trigger_volume_pub = node.create_publisher::<T>(&format!("{prefix}/trigger_volume"), qos)?;
>     |                                                   +++++
> 
> error[E0283]: type annotations needed for `Publisher<T>`
>    --> src/actor_node/traffic_sign.rs:15:9
>     |
> 15  |     let trigger_volume_pub = node.create_publisher(&format!("{prefix}/trigger_volume"), qos)?;
>     |         ^^^^^^^^^^^^^^^^^^        ---------------- type must be known at this point
>     |
>     = note: cannot satisfy `_: r2r::msg_types::WrappedTypesupport`
> note: required by a bound in `Node::create_publisher`
>    --> /home/yirong/.cargo/git/checkouts/r2r-8618b4115035fdcb/6644562/r2r/src/nodes.rs:568:12
>     |
> 568 |         T: WrappedTypesupport,
>     |            ^^^^^^^^^^^^^^^^^^ required by this bound in `Node::create_publisher`
> help: consider specifying the type argument in the function call
>     |
> 15  |     let trigger_volume_pub = node.create_publisher::<T>(&format!("{prefix}/trigger_volume"), qos)?;
>     |                                                   +++++
> 
> error[E0282]: type annotations needed
>   --> src/actor_node/vehicle.rs:32:9
>    |
> 32 |     let forward_ackermann = forward_control_cmd(
>    |         ^^^^^^^^^^^^^^^^^
> ...
> 45 |         future: forward_ackermann.boxed(),
>    |                 ----------------- type must be known at this point
>    |
> help: consider giving `forward_ackermann` an explicit type
>    |
> 32 |     let forward_ackermann: _ = forward_control_cmd(
>    |                          +++
> 
> warning: unused import: `FutureExt`
>  --> src/actor_node/vehicle.rs:9:34
>   |
> 9 | use futures::{future::BoxFuture, FutureExt, Stream, StreamExt};
>   |                                  ^^^^^^^^^
>   |
>   = note: `#[warn(unused_imports)]` on by default
> 
> Some errors have detailed explanations: E0282, E0283, E0433.
> For more information about an error, try `rustc --explain E0282`.
> error: could not compile `carla_autoware_bridge_plus` due to 7 previous errors; 1 warning emitted

The errors were like:
   failed to resolve: could not find `moveit_msgs` in `r2r`
   failed to resolve: could not find `carla_msgs` in `r2r`
   error[E0283]: type annotations needed for `Publisher<T>`

What can I do to resolve these carla_autoware_bridge_plus error?
Thank you.

**Comment by jerry73204** [comment]
It's due to missing dependencies. `moveit_msgs` comes from preinstalled ROS package. `carla_msgs` comes from a git submodule inside `ros-bridge/` which is usually ignored.

I updated the document. Please `git checkout mention-movit-in-doc` and stick to that commit for now, as the `master` can change occasionally.

https://github.com/NEWSLabNTU/carla_autoware_bridge_plus/tree/mention-movit-in-doc

**Comment by yironglin** [comment]
Hi @jerry73204 , thanks for updating the installation guide.
After checking `autoware/` branch and git submodule `ros-bridge/`, I finished building the bridge without errors!
